# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NR' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Socket.IO-Client-Swift', '~> 11.0.2' # Or latest version

  # Pods for NR

  target 'NRTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NRUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
